# Generated by Django 6.0.1 on 2026-01-20 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('rule_type', models.CharField(choices=[('pattern', 'Pattern'), ('python', 'Python'), ('hybrid', 'Hybrid')], max_length=20)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('severity', models.CharField(blank=True, max_length=20, null=True)),
                ('yaml_content', models.TextField(blank=True, null=True)),
                ('tags', models.CharField(blank=True, max_length=500, null=True)),
                ('enabled', models.BooleanField(default=True)),
                ('remediation_template', models.TextField(blank=True, null=True)),
                ('compliance_frameworks', models.CharField(blank=True, max_length=500, null=True)),
                ('framework_mappings', models.JSONField(blank=True, null=True)),
                ('risk_weight', models.FloatField(default=1.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Audit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Completed', 'Completed'), ('Failed', 'Failed'), ('Cancelled', 'Cancelled'), ('Partial', 'Partial')], default='Pending', max_length=20)),
                ('device_identifier', models.CharField(max_length=255)),
                ('device_family', models.CharField(blank=True, max_length=255, null=True)),
                ('config_file', models.CharField(blank=True, max_length=255, null=True)),
                ('parsed_config', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('snapshot_name', models.CharField(blank=True, max_length=255, null=True)),
                ('device_hostname', models.CharField(blank=True, max_length=255, null=True)),
                ('device_model', models.CharField(blank=True, max_length=255, null=True)),
                ('device_firmware', models.CharField(blank=True, max_length=255, null=True)),
                ('device_location', models.CharField(blank=True, max_length=255, null=True)),
                ('device_make', models.CharField(blank=True, max_length=100, null=True)),
                ('device_type', models.CharField(blank=True, max_length=100, null=True)),
                ('progress', models.JSONField(blank=True, null=True)),
                ('parent_audit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='core.audit')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Finding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.CharField(max_length=20)),
                ('message', models.TextField()),
                ('config_path', models.TextField(blank=True, null=True)),
                ('remediation', models.TextField(blank=True, null=True)),
                ('remediation_status', models.CharField(choices=[('Not Started', 'Not Started'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Verified', 'Verified')], default='Not Started', max_length=20)),
                ('remediation_notes', models.TextField(blank=True, null=True)),
                ('audit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='core.audit')),
                ('parent_finding', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.finding')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='core.rule')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
